### PR TITLE
Feature/306 company feed comments

### PR DESCRIPTION
**Pull request by YevheniiMusiievskyi**

### CODE REVIEW

**Comment by severynenko** [comment]
A number of comments can be seen only on a separate news item page. Also couldn't edit and delete comments.

**Comment by severynenko** [comment]
And add news item endpoint access to employee role

**Comment by EugeneMusievskyi** [comment]
fixed

**Comment by TheBestTvarynka** [comment]
Can you create a new feed item? Because I get an error (NullPointerException)?
But on dev branch, I can create a new one without problems.

**Review by TheBestTvarynka — APPROVED** [review]

**Pull request merged**
