### PR TITLE
Password reset UI

### PR DESCRIPTION
**Pull request by TheBestTvarynka**

### CODE REVIEW

**Comment by TheBestTvarynka** [comment]
What I should also change?

**Comment by TheBestTvarynka** [comment]
What I should also change?

**Comment by TheBestTvarynka** [comment]
https://imgur.com/a/XfdPSFe

**Review by muroslavko — APPROVED** [review]

**Comment by MaksymSlobodianyk** [comment]
> What I should also change?

Maybe add header?

**Comment by TheBestTvarynka** [comment]
https://imgur.com/a/XW446lq

**Review by muroslavko — APPROVED** [review]

**Pull request merged**
