### PR TITLE
Feature/344 remove random suffix from subdomain

### PR DESCRIPTION
**Pull request by grytsiuko**

### CODE REVIEW

**Comment by marchuk0** [comment]
subdomain for companies "BSA" and "bsa" should be different, so we use random suffix

**Comment by lenazelenaya** [comment]
Mb we could add random suffix only when company with the same name, but with different case, exists?
for ex. if "bsa" exists, then will add "BSA" with subdomain "bsa-2asda" ?

**Comment by grytsiuko** [comment]
I have changed unique constraint, so it ignores case when checks if company name exists

**Comment by grytsiuko** [comment]
So user can't create BSA and bsa companies. It leads to more laconic subdomain

**Review by AlexandrKarpachov — APPROVED** [review]

**Pull request merged**
